name: Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always
  RUST_LOG: info

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install

      - name: Check types
        run: yarn tsc

      - name: Check formatting
        run: yarn lint:check

      - name: Run tests
        run: yarn test
